/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#faf8ff",
        "surface-container-highest": "#dae2fd",
        "secondary-fixed-dim": "#a4c9f9",
        "tertiary-fixed-dim": "#a1d1b8",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#afc6ff",
        "surface-container-lowest": "#ffffff",
        "on-background": "#131b2e",
        "outline-variant": "#c4c6d1",
        "secondary-fixed": "#d2e4ff",
        "tertiary-fixed": "#bdedd4",
        "secondary-container": "#aacfff",
        "on-secondary-fixed-variant": "#204972",
        "on-surface-variant": "#44464f",
        "error-container": "#ffdad6",
        "secondary": "#3b618b",
        "tertiary": "#001c11",
        "tertiary-container": "#003322",
        "inverse-on-surface": "#eef0ff",
        "on-tertiary-container": "#6f9d86",
        "on-tertiary": "#ffffff",
        "surface-container": "#eaedff",
        "on-surface": "#131b2e",
        "on-primary": "#ffffff",
        "on-primary-container": "#7a93cd",
        "surface-container-high": "#e2e7ff",
        "on-primary-fixed": "#001944",
        "on-error": "#ffffff",
        "primary-container": "#0a2a5e",
        "background": "#faf8ff",
        "error": "#ba1a1a",
        "inverse-primary": "#afc6ff",
        "on-secondary-container": "#325882",
        "surface-container-low": "#f2f3ff",
        "primary-fixed": "#d9e2ff",
        "surface-dim": "#d2d9f4",
        "inverse-surface": "#283044",
        "on-secondary-fixed": "#001d36",
        "on-primary-fixed-variant": "#2b457a",
        "on-tertiary-fixed-variant": "#224f3c",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#002115",
        "surface": "#faf8ff",
        "surface-variant": "#dae2fd",
        "primary": "#00163c",
        "surface-tint": "#445d94",
        "outline": "#747780"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "margin": "2rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "0.75rem",
        "space-xl": "2.5rem",
        "gutter": "1.25rem",
        "space-sm": "0.5rem",
        "margin-mobile": "1rem"
      },
      fontFamily: {
        sans: ["Plus Jakarta Sans", "sans-serif"],
        display: ["Outfit", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-sm": ["Outfit"],
        "display-mobile": ["Outfit"],
        "headline-lg-mobile": ["Outfit"],
        "body-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Outfit"],
        "label-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-md": ["Outfit"],
        "eyebrow": ["Outfit"]
      }
    }
  },
  plugins: []
}
