# Generated by Django 5.1.15 on 2026-09-25 18:54

import booking_api.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('location_type', models.CharField(default='all nairobi', max_length=50)),
                ('location_display', models.CharField(default='Karen Studio Sanctuary, Nairobi', max_length=200)),
                ('price_kes', models.PositiveIntegerField(default=3500)),
                ('price_eur', models.PositiveIntegerField(default=40)),
                ('image', models.ImageField(blank=True, help_text='Uploaded service photo saved in media storage (JPG, PNG, WebP up to 10MB)', null=True, upload_to=booking_api.models.service_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('image_url', models.URLField(blank=True, help_text='Optional external image fallback URL', max_length=500, null=True)),
                ('description', models.TextField()),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('capacity', models.CharField(default='Small Group (4–8)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('target_entity', models.CharField(max_length=100)),
                ('target_id', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=30)),
                ('payment_method', models.CharField(default='mpesa', max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('total_amount', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('coach_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking_api.service')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='daraja_mpesa', max_length=50)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='KES', max_length=10)),
                ('phone_number', models.CharField(max_length=50)),
                ('status', models.CharField(default='initiated', max_length=30)),
                ('raw_callback_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='booking_api.booking')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slot_date', models.DateField(db_index=True)),
                ('start_time', models.CharField(max_length=20)),
                ('period', models.CharField(default='Morning', max_length=20)),
                ('location_name', models.CharField(default='Karen Sanctuary', max_length=200)),
                ('total_capacity', models.PositiveIntegerField(default=4)),
                ('spots_left', models.PositiveIntegerField(default=4)),
                ('is_full', models.BooleanField(default=False)),
                ('banner_image', models.ImageField(blank=True, help_text='Custom session/masterclass promotional banner (JPG, PNG, WebP up to 10MB)', null=True, upload_to=booking_api.models.session_banner_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('banner_url', models.URLField(blank=True, help_text='Optional external banner fallback URL', max_length=500, null=True)),
                ('session_theme', models.CharField(blank=True, help_text='e.g. Full Moon Sound Immersion or Pelvic Floor Masterclass', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='booking_api.service')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='booking_api.timeslot'),
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(default='5-Session Studio Pass', max_length=255)),
                ('total_sessions', models.PositiveIntegerField(default=5)),
                ('remaining_sessions', models.PositiveIntegerField(default=5)),
                ('valid_until', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('client', 'Client / Member'), ('coach', 'Coach / Practitioner'), ('studio_admin', 'Studio Administrator'), ('superadmin', 'Platform Superadmin')], db_index=True, default='client', help_text='Role-Based Access Control principal', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, help_text='User profile picture (JPG, PNG, WebP up to 5MB)', null=True, upload_to=booking_api.models.user_avatar_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('bio', models.TextField(blank=True, help_text='Short bio or personal wellness focus')),
                ('emergency_contact', models.CharField(blank=True, max_length=255)),
                ('somatic_notes', models.TextField(blank=True, help_text='Client pelvic, injury, or somatic disclosures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['service', 'slot_date'], name='booking_api_service_812596_idx'),
        ),
    ]
