# Generated by Django 5.1.15 on 2026-09-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_position',
            field=models.CharField(choices=[('center', 'Center'), ('top', 'Top Focus'), ('bottom', 'Bottom Focus'), ('left', 'Left Alignment'), ('right', 'Right Alignment')], default='center', help_text='Object position focal alignment for avatar image', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_shape',
            field=models.CharField(choices=[('circle', 'Circle'), ('squircle', 'Squircle / Rounded'), ('square', 'Classic Square')], default='circle', help_text='Display shape preference for profile photo', max_length=20),
        ),
    ]
